### PR TITLE
Trading issue#39

### PR DESCRIPTION
**Pull request by ajlaroche**
Added starter server file, front-end trading function, routes to back-end, and request to 3rd party service for price quote.

Next step is to add database routes.

### CODE REVIEW

**Comment by lmcneel** [comment]
in clients the pages/Trading folder is mispelled. That also looks like a component file and thus should be in the components folder.

Please fix this, not merging

**Comment by lmcneel** [comment]
The code to define the route for react is in both server.js and in routes/index.js. 

It should only be in one place

**Comment by ajlaroche** [comment]
I fixed items 1 and 2  and most of the lint errors.  A lot of them are from the starter React file and there were a couple that I did not understand.  I assume all those starter React file will all be replaced.

I will submit another pull request without fixing the React files and we can talk through the couple of lint errors that did not make sense to me during class tomorrow.

**Comment by ajlaroche** [comment]
Just to be clear, I did not create a new request.  I just push the updates to this one.  Let me know if that did not work.

**Pull request merged**
